name: Scrape and Update JSON

on:
  schedule:
    - cron: '0 0 * * *'  # Todos los días a medianoche UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper script
        run: |
          python3 api/api.py

      - name: Commit and push the new JSON file
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "yotta-public"
          git config --global user.email "jnune97vlc@gmail.com"
          git add api/eventos.json
          git diff --quiet || (git commit -m "Update eventos.json" && git push https://${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main)
