name: Scrape and Update JSON

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecuta el flujo de trabajo todos los días a la medianoche UTC.
  push:
    branches:
      - main  # Ejecuta el flujo de trabajo cuando se hace un push a la rama 'main'.
  workflow_dispatch:  # Permite ejecutar manualmente el flujo de trabajo desde la interfaz de GitHub.

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Especifica la versión de Python que deseas usar.

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper script
        run: |
          python3 api/api.py  # Asegúrate de que tu script esté nombrado correctamente y esté en el repositorio.
      - name: Debug GH_TOKEN
        run: echo "GH_TOKEN is ${GH_TOKEN:+'defined'}"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
      - name: Print eventos.json content
        run: | 
          cat api/eventos.json

      - name: Commit and push the new JSON file
        run: |
          git config --global user.name "yotta-public"
          git config --global user.email "jnune97vlc@gmail.com"
          git add api/eventos.json
          git commit -m "Update eventos.json" || echo "No changes to commit"
          git push https://github-actions:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main


      - name: Debug eventos.json
        run: |
          cat api/eventos.json

      - name: Show git diff
        run: |
          git diff api/eventos.json

