name: Scrape and Update JSON

on:
  schedule:
    - cron: '0 0 * * *'  # Esto ejecuta el flujo de trabajo todos los días a la medianoche UTC.
  push:
    branches:
      - main  # Esto ejecuta el flujo de trabajo cuando se hace un push a la rama 'main'.
  workflow_dispatch:  # Permite ejecutar manualmente el flujo de trabajo desde la interfaz de GitHub.

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Especifica la versión de Python que deseas usar.

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper script
        run: |
          python3 api/api.py  # Asegúrate de que tu script esté nombrado correctamente y esté en el repositorio.

      - name: Commit and push the new JSON file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add api/eventos.json  # Asegúrate de que la ruta al archivo JSON es correcta
          git commit -m "Update eventos.json"
          git push origin main  # Empuja los cambios a la rama principal del repositorio
